
-- Create the availability group
CREATE AVAILABILITY GROUP MyTestAG
   WITH (CLUSTER_TYPE = NONE)
   FOR DATABASE MyTestDB
   REPLICA ON
      N'sql1' WITH
         (ENDPOINT_URL = 'TCP://172.20.0.10:5022',
         AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
         FAILOVER_MODE = MANUAL,
         SEEDING_MODE = AUTOMATIC),
      N'sql2' WITH
         (ENDPOINT_URL = 'TCP://172.20.0.11:5022',
         AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
         FAILOVER_MODE = MANUAL,
         SEEDING_MODE = AUTOMATIC),
      N'sql3' WITH
         (ENDPOINT_URL = 'TCP://172.20.0.12:5022',
         AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
         FAILOVER_MODE = MANUAL,
         SEEDING_MODE = AUTOMATIC);
GO
